### ISSUE TITLE
マッチメイク係についてやっていることを書く

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#13]
https://github.com/xerosbaseball/terms/blob/main/content/role/matchmaking.ja_jp.md

**Comment by Xeros18** [comment]
更新途中なので、まだ残しておいてください

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/pull/127

**Comment by susumutomita** [comment]
クローズしてよければクローズしてください
