### ISSUE TITLE
JAXリーグ係についてやっていることを書く

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#14]
https://github.com/xerosbaseball/terms/blob/main/content/role/jax_league.ja_jp.md

**Comment by Xeros18** [comment]
JAXリーグ係を記載してみました。
マークダウン形式、やってみると面白いですね。

でも反映されていない気がする

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/pull/51
がプルリク
