### ISSUE TITLE
一人が担える役割の上限を設けるかどうか決める

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#162]
現状少なくとも1つ以上の役割を担ってくださいと希望を取ったら、一人で5-6個もやるという人もいれば1つだけやるという人が現れた。
結果負荷の偏り、ノウハウの属人化が生まれてしまいそうになっている。
https://github.com/xerosbaseball/terms/issues/160
で記載した役割の人数枠を決めるのとあわせて一人が担える役割の上限を設けて見てはいかが？

**Comment by susumutomita** [comment]
まず必須な役割とそれ以外を整理する。
その上で上限を2個までにする。そうじゃないと今回みたいに1人で4個も5個もやりますって人が現れてノウハウが共有されない、個人に依存する運営体制になる

**Comment by Xeros18** [comment]
いま、メンバーが９人だから、上限作るのは厳しい気がしますよね。
苦手な係を渡して、その方のモチベーションが下がり、参加率が減る方が怖いです。
正と副にしてカバーしあうとか、覚えていってもらうしかないと思います。

藤沢市の場合は、抽選結果のハガキが代表者に届き、体育館へ支払いに行く必要があるので、こちらはミナミさんとエトウさ
んにお願いするしかないと思うのです。

**Comment by susumutomita** [comment]
無理な係をやらないように工夫はいると思いますけどだからといって今までのように一部の人に負荷が集中するのをよしとするべきではありません。
一番誰を大事にしなきゃいけないかって考えると参加率が高くて運営に協力してくれる人だと考えています。
その貢献度が高い人が燃え尽きてしまうこれは絶対避けないといけないことでこれだけチームが大変な状況なのに支える気があまりない人を慮らなくてもいいのではなかろうか
藤沢が手続きのために体育館へ支払にいくことが必要で大変と言うのであれば藤沢のグラウンドを取らない選択肢だってありますし。
いくつも選択肢はあるかなと思います。

**Comment by susumutomita** [comment]
正と副を設けるもありですけどマッチメイクで正、副設けだけど結局正の人がやっちゃってあまり機能しなかったことを考えると副担当置くだけでうまくいくかはちょっとわかんないですね。少し工夫が必要そうかなと
例えば経験した人と組んでもらうようにするとかサポート入るとかはあった方が良さそうです。
もしくは去年経験した人を副にして別の人が正をやるとかも良さそう

**Comment by susumutomita** [comment]
ただ、いろんな係りで正副考え出すとその組み合わせを考えるのが大変だから正だけ決めてその係の経験者がサポートする文化を作っていくのが良さそうに感じる。

**Comment by Xeros18** [comment]
仮にマッチメイクの担当を私がはずれたとしても、色々なチームの連携先を知っているのは私ですし、お誘いは私にくると思います。
私が副になって、正の人とやっていてフォローするのがよいかもです。

マッチメイクは大変なので、正副制にして、誰かに正でやってもらって、私が支援の副になるのが現実的な気がします。

**Comment by susumutomita** [comment]
これまでの繋がりもあるのでしばらくは旧担当に連絡が入ることは想定されますね。
その時は旧担当が新担当に引き継ぐように動く必要はあるでしょうな。

**Comment by susumutomita** [comment]
各役割の人数については別にIssueを作成しているので
https://github.com/xerosbaseball/terms/issues/160
で履歴を残すようにしましょうか。

**Comment by susumutomita** [comment]
まずは
一人に負荷が集中して燃えつきないように一人が全部やらない、できないように上限を設けることについては良いでしょうか。
各係の内訳は別で話そうかなと
https://github.com/xerosbaseball/terms/issues/160

**Comment by susumutomita** [comment]
体制決まったのでクローズ
