### ISSUE TITLE
チームHPをどれにするか決める

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#163]
ページ乱立問題をどうするか決める必要あり。
チームの顔となるものなのできちんとメンテナンス更新する必要がある。
現状以下の4つがあるが3,4についてはチームとしてメンテナンスはしていない状態。

1. [規約類を載せたページ](https://xerosbaseball.github.io/terms/)
2. [Play](https://tmhub.jp/teams/37796/intro)
3. [Teams](https://teams.one/teams/xeros)
4. [行くぜ!](https://www.ikz.jp/ikz/s.cgi?no=17817)

**Comment by Xeros18** [comment]
#33と#89さんは、行くぜ！の問い合わせ経由で連絡くれました。過去に連絡くれたのはこの２名です。
実績のあるページは「行くぜ！」です。

Playよりは、Teamsの方がスケジュールと、過去の対戦結果が見やすいです。
第三者が、うちのチームの今後のスケジュール活動履歴を見る分には見やすいかと思います。
・浜見平オーキス
・UNLIMTED
はうちのTeamsのページをみてスケジュールと、活動履歴をみていました。

まあ、回数的には少ないので、決めてくれたら従います。
Teams更新するのは個人的に苦ではないので。

**Comment by susumutomita** [comment]
Teams,いくぜ廃止で

**Comment by Xeros18** [comment]
分かりました

**Comment by Xeros18** [comment]
Teamsは消せましたけど、行くぜ消せないですね。
他のチームもだから残しているのかな？

**Comment by susumutomita** [comment]
そうか消せないようならHugoのページにSEO対策を入れて一番上に来るようにしないといけないですな

**Comment by susumutomita** [comment]
削除できるみたいよ
https://www.ikz.jp/qa.html

> Q2.チーム登録やホームページを削除したい。
　A2.チーム情報変更画面よりチーム名を「削除希望」としておいてください。
　　HPだけ削除したい場合も一旦削除希望に変更し、再度新規でチーム登録をしてください。
　　(チームIDはチーム紹介ページに記載しています。パスワードはQ12参照）
　　上記で削除できない場合は、下記Q26を参照してみてください。

**Comment by susumutomita** [comment]
削除できた
https://www.ikz.jp/hp/xeros/
<img width="793" alt="image" src="https://user-images.githubusercontent.com/11481781/207862188-89024656-bbee-4328-a36a-eb11292924e1.png">

**Comment by Xeros18** [comment]
ありがとうございます！

**Comment by susumutomita** [comment]
規約のページがGoogle検索で"藤沢　草野球チーム"、"横浜 草野球チーム"で上位にくるようにSEOは必要。別途チケット切ってやる

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/issues/165
SEOはこっちでチケット切ったのでこのチケットはクローズ
