### ISSUE TITLE
リーグ戦決める

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#173]

**Comment by susumutomita** [comment]
https://bb.vcuda.net/ysl/kiyaku
土曜日、横浜市中心、審判ありとニーズ近い
ヘルメット着用を義務付けているのもちゃんとしていていいと思う。

**Comment by Xeros18** [comment]
湘南ライナーズが参加しているところですよね、私もここを記載しようと思ってました。
試合の消化具合がよくないとライナーズから聞いたことがあるのと、参加チームはXerosよりも強いチームですね。

**Comment by susumutomita** [comment]
最近の取り組みを見ていると強い相手とやって刺激をもらったほうがいいかなと思うのと新しいつながりを広げるっていうのも良いのかなって

**Comment by susumutomita** [comment]
問題は新規加入を募集しているかかな

**Comment by Xeros18** [comment]
＞最近の取り組みを見ていると強い相手とやって刺激をもらったほうがいいかなと思うのと新しいつながりを広げるっていうのも良いのかなって
　JAXリーグで勝てないという意見もありましたよ。
　
ライナーズの村瀬さんに聞く事は可能。

**Comment by susumutomita** [comment]
> JAXリーグで勝てないという意見もありましたよ。

そうです、そうです、だから強いところとやらないと勝てるようにはならないよと。勝てないから弱いところとやるでは勝てるようにはならないです。勝ちたいなら強いところとやって、強さの理由を学ばないとどうしようもないなと。

**Comment by susumutomita** [comment]
あとはちゃんとしたリーグは基本強いチームが参加しているので、ちゃんとしたリーグでやりたいなら強くならないと楽しめないです。

**Comment by Xeros18** [comment]
強いリーグに行くのか、JAXリーグのままでよいのかは、メンバーの意見を聞きたいですね。
何処も強そうですね。

https://ybl.main.jp/contract/
=>攻撃側審判

https://cube-leage.com/
=>参加費12万 審判付　東俣野だったり、日曜日開催だったり

https://bb.vcuda.net/246/
=>派遣審判呼ぶとある

https://texas-league.1net.jp/

**Comment by susumutomita** [comment]
そうですね、聞いた上で決めてあげた方がいいでしょうね。
あとであーだこーだ言われてもなあと

**Comment by susumutomita** [comment]
リーグ戦云々はマッチメイクが楽かもって発想から来てるから、月三試合できればリーグ自体にあまりこだわりはないかもしれないですね。
勝てない云々は言い出すかもしれんが弱くてちゃんとしているリーグなんてないよ。
モチベーション高いチームで弱いって超レアなわけで

**Comment by susumutomita** [comment]
あとはリーグに何を求めるかは整理した方がいいかもなと
- 土曜日午前中
- 派遣審判あり
- 神奈川県
- うちでも勝てるチーム
- 調整しやすさとかマナーがちゃんとしているチームで構成されている
くらい？

**Comment by susumutomita** [comment]
リーグじゃないけど
[MIZUNO BASEBALL DREAM CUP](http://pridejapan.net/mizuno.bdc/about.html)は参加費無料なのでエントリーしておきたいところ

**Comment by susumutomita** [comment]
他の人からも特に続報はなかったので、一通り出揃った感じかな。
- リーグ戦はJAXリーグに参加
- [MIZUNO BASEBALL DREAM CUP](http://pridejapan.net/mizuno.bdc/about.html)は参加費無料だしとりあえずエントリーする
で決定かしら？

**Comment by susumutomita** [comment]
JAXリーグ参加するだと平塚での試合もそれなりにあるけど、人数集まんのかな？
今の様子だと集まる感じはないからJAXリーグは今年は見送らないと厳しそう。不戦敗ばかりは辛かろう
