### ISSUE TITLE
スポーツ保険の調査結果を反映する

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#175]
今年からスポーツ保険の加入を検討するので仕組み、どの保険に入るのか等々調査した結果を反映する必要あり

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/pull/174

**Comment by xeros5** [comment]
色々と対応ありがとうです。　この手の部類は寺小屋が必要ですな。。。

今後の進め方で確認ですが、先ずは以下のプルリクを削除またはキャンセルするべきなのかしら？
https://github.com/xerosbaseball/terms/pull/174

用意してもらったissues（スポーツ保険の調査結果を反映する #175）で作業を進める思い。。。
一度テレカンが必要ですかね。。。。

**Comment by susumutomita** [comment]
1. https://github.com/xerosbaseball/terms/pull/174
でプルリクエストを出しているinsurance.mdの修正を完了させる。
2. プルリクエストをマージする
3. Issueをクローズする
の順で進めます。

テレカンも必要に応じてやりましょうか

**Comment by xeros5** [comment]
一度マージ願います。（全体の７０％完了）

**Comment by xeros5** [comment]
あれ？　マージされとる。。。

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/pull/176
