### ISSUE TITLE
平塚市の返金処理を簡単にできないか？

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#202]
平塚市のカードの所有者と違う人がグラウンドの予約担当となっていて、利用料金を支払った後にグラウンドをキャンセルしたときの返金処理が毎回カードの所有者にお願いしないといけなくてめんどくさい。

**Comment by Xeros18** [comment]
平塚だけでなく、藤沢市も代表者と連絡者で分かれていて、私も藤沢のカード１枚担当になっていて、お金を払いにいったりします。

キャンセルする、グランド変えるとするのは面倒な処理が発生するので、手違いが起こるリスクが発生します。
このグランドを使うと決めたら、キャンセルとかあまりせずに使うのが良いのではと思います。

ちなみに去年のキャンセルは、辻堂南部の１回だけだったのではと思います。

**Comment by susumutomita** [comment]
平塚市のカードの所有者に予約もしてもらうようにしたのでこの件はクローズ。
こうすると本予約時にお金を払った人が返金時にお金を受け取るのでお金の受け渡しがスムーズになる。

**Comment by susumutomita** [comment]
藤沢市の話は別のIssueを立ててやりましょう。
