### ISSUE TITLE
Xerosの係一覧

### ISSUE THREAD

**Issue by Xeros18** [xerosbaseball/terms#30]
Xerosでは、メンバーがそれぞれ分担して以下の係があります。
なかなか参加できなくても各自担当できる係があります。

係の種類と、活動頻度と活動内容の概要をここに記載する予定
グランド確保係　月末１回（予約）　月初１回（確定処理）

**Comment by susumutomita** [comment]
いいですね
概要は
https://github.com/xerosbaseball/terms/blob/main/content/role/_index.ja_jp.md
に書いてあるので、このファイルに説明を追記するのが良いと思います。
Issueに記載内容を書いていくより実際にファイルを編集して[プルリクエスト](https://backlog.com/ja/git-tutorial/pull-request/01/)を出してもらってプルリクエストのレビューで中身を見ていったほうが書きやすいかなと。行ごとにコメントできるし、実際のコードベースで話しができますしね。

あと詳細については
https://github.com/xerosbaseball/terms/tree/main/content/role
配下のファイルたちに書かれているので、適宜書けそうな人にお願いして進めるのが良さそうかなと

**Comment by Xeros18** [comment]
自分、会社のPCしかないのですが、GitBashのインストール必要ですかね？

Webブラウザで編集できたりします？

↓以下を修正したいのですけれど。
https://github.com/xerosbaseball/terms/blob/main/content/role/_index.ja_jp.md

**Comment by susumutomita** [comment]
ブラウザから編集できますよもちろん

**Comment by susumutomita** [comment]
スマホからもできますよ。実際スマホしか持ってない人からプルリク出してもらってますしね

**Comment by Xeros18** [comment]
係の表を追記しました、各係のURL？とマージ可能ならマージして欲しいです。

**Comment by susumutomita** [comment]
ありがとうございます。
修正依頼だしたので修正お願いします。修正が終わったらマージしちゃいましょう。
あとプルリクのリンクをコメントに書くか、Issueのリンクをプルリクに書いておいてほしいです。Issueのリンクをプルリクに書いておくとプルリクがマージされると自動でIssueもクローズになるんですよ
https://github.com/xerosbaseball/terms/pull/56

**Comment by susumutomita** [comment]
あと新たに項目、今回の場合だと係が増えたときは
- Issueを切って管理できるようにする
- 目次に項目のリンクを追加 
- 表示の並び順も調整する
が必要ですね。
やること多いので別Issueにするのが良さそうです

**Comment by Xeros18** [comment]
一度プルリクしたやつの修正方法がわからないです。

Issueをどこに記載すればよいのかがわからないです。
コメントにいれちゃったけれどあっているのか不明

**Comment by susumutomita** [comment]
IssueはIssuesタブで作ります。
プルリクの修正方法はプルリクの対象ブランチを更新します。
このケースの場合だと
プルリク
#56
の対象ブランチはXeros18-patch-1です。このブランチに修正を追加します。
https://github.com/xerosbaseball/terms/tree/Xeros18-patch-1

質問の詳細な説明はすべてインターネット上に書かれているので自分で調べられるようになっておくといいですよ
例えば
https://backlog.com/ja/git-tutorial/pull-request/06/
https://backlog.com/ja/git-tutorial/pull-request/07/
らへんの話です

**Comment by Xeros18** [comment]
調べた方が良いのは分かりますが、これをメンバー全員にさせるのはどうかなと思います。
ハードル高いと思う人はでてきて去っていく人が出てこないかを思います。

**Comment by Xeros18** [comment]
https://github.com/xerosbaseball/terms/blob/main/content/role/_index.ja_jp.md
↑
これを修正してとissueは分かりやすいので、編集はできるのです。

Pull requestsの画面になると、どれをEditすればよく分からないから困っているのです。
Pull requestsを却下して一から修正する方が早い気がしています。

**Comment by susumutomita** [comment]
プルリクの修正方法はブランチを更新するというのは理解できましたか？
どこに詰まっているのかが分からないので聞いています。
質問内容を見ているとGitHubの使い方というより
Gitの使い方を知らないようには見えています。

**Comment by Xeros18** [comment]
Gitの使い方を知らないです。

・ブランチのファイルが何処から参照するのかがわからない。
・PullRequestに１件あるのは見えていて、そこを開いてもブランチのファイルにたどり着けない。

　冨田さんのissueでこのファイルを修正してと言われていて開けて、Editが非常に分かりやすかったです。

**Comment by Xeros18** [comment]
https://github.com/xerosbaseball/terms/blob/main/content/role/_index.ja_jp.md
↑このファイルをEditで修正して、更新（プルリク）しかできないです。

**Comment by susumutomita** [comment]
メンバー全員に期待はしてなくて所謂ITエンジニアのバックグラウンドがある人とそうでない人でお願いの仕方は変えないといけないでしょうね。
GitもGitHubもソフトウェアに携わる人で知らない人いるのかな？くらいソースコード管理に浸透しているツールだと思っていて馴染みのあるツールかなって認識

**Comment by susumutomita** [comment]
PCで編集していますか？それともスマホですか？
- git checkout ブランチ名でブランチをチェックアウト
- ファイル修正
- git add ファイル名
- git commit -m "コメント"
- git push
この流れで編集します

**Comment by Xeros18** [comment]
ソースは作成しないので。使ったことないので。
ブランチは見えるのですが、該当ファイルが分からない。

![xeros18-1](https://user-images.githubusercontent.com/116900182/199462853-6bb52c6c-05de-4b95-b700-aeef97fd0cf1.png)

**Comment by Xeros18** [comment]
PCでブラウザです。

**Comment by Xeros18** [comment]
画面を貼りつけました。

**Comment by Xeros18** [comment]
issueをみるとこんな感じです。

![xeros18-2](https://user-images.githubusercontent.com/116900182/199463727-dcad9b19-cf5e-4cd5-8f9c-2a6352dcc767.png)

**Comment by susumutomita** [comment]
了解です。
まずはソースコードをローカルに持ってきましょうか。

https://docs.github.com/ja/repositories/creating-and-managing-repositories/cloning-a-repository

ここを読んでgit cloneでローカルにレポジトリをクローンしましょうか。

画面から編集するの僕知らないし

**Comment by susumutomita** [comment]
次にエディタをダウンロードしましょう

https://azure.microsoft.com/ja-jp/products/visual-studio-code/
を入れてください

**Comment by Xeros18** [comment]
会社PCなので、エディタいれたくないのです。すみませんわがまま言って。
Web画面は編集できて、Previewもできて快適なのです。プルリクの修正だけがわからないんです。

土曜日、南さんに見てもらおうかな。

**Comment by susumutomita** [comment]
ああそうなんですな

https://docs.github.com/ja/repositories/working-with-files/managing-files/editing-files

ここに書いてあるようにブランチの選択をmainじゃなく修正対象のブランチを選択していけませんかね

ファイルパスは
content/role/_index.ja_jp.md

**Comment by susumutomita** [comment]
![image](https://user-images.githubusercontent.com/11481781/199468979-e84d6a62-3b25-4da9-bf8a-a1e5cecefaa3.png)

こんな感じ

**Comment by Xeros18** [comment]
おーーー！
見つけました。

ありがとうございます。お騒がせしました。

これで私も困った人に教えれます。

**Comment by susumutomita** [comment]
よかったです。頑張って

**Comment by susumutomita** [comment]
この学びを是非
https://github.com/xerosbaseball/terms/issues/16
に書いていただけると助かります

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/pull/68
