### ISSUE TITLE
修正の出し方について記載する

### ISSUE THREAD

**Issue by susumutomita** [xerosbaseball/terms#31]
README.mdを用意しても読まない
ページで説明しないとダメそうなことがわかった

**Comment by Xeros18** [comment]
編集したページ（ファイル）の実際にブラウザからPreviewを見る方法を知りたい。

ファイルの書式はなんというので調べたらよいか教えて欲しい。

IT関係じゃない人は書いてとお願いしても難しい気がします。
書いてと依頼するよりネタくださいが良いのではと思いました。

**Comment by susumutomita** [comment]
ファイル形式はマークダウンですよ。.mdの拡張子だし
マークダウン形式って何かはGoogleに聞いてください。

**Comment by susumutomita** [comment]
IT関係者は難しいと思ってたんですけど経理の人ができたのでファイルの編集は誰でもできると思います。
ただ、ファイルの作成はHugoのコマンドを使う必要があるのでこれはREADME.mdに書いてある内容を理解できる人だけにお願いする感じかなと思います。
なので今のお願いの仕方はファイルを作成して、Issueにどのファイルを編集すればいいかファイルのリンクを追加してあります。

**Comment by Xeros18** [comment]
ありがとうございます。
マークダウン形式調べて記載します。

**Comment by susumutomita** [comment]
https://github.com/xerosbaseball/terms/pull/49
書いた
